# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		John Hatvani
tagline:	'Mobile Software Engineer'
description:	'xx'
url:		johnhatvani.github.io
commentsystem:	google
disqus:		example

author:
  name:		'Ian Camporez Brunelli'
  url:		https://google.com/+IanCamporezBrunelli

paginate:	10

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/j_hatvani
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/johnhatvani
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+IanCamporezBrunelli
    desc:	Stack Overflow

  - icon:	googleplus-alt
    url:	http://google.com
    desc:	Connect

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	John Hatvani
  url:		johnhatvani.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
