# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               John Hatvani
tagline:             'website of John Hatvani'
baseurl:             /

twitter:            'http://www.twitter.com/j_hatvani'
linkedin:           'http://au.linkedin.com/in/jhatvani'
stackoverflow:      'http://stackoverflow.com/users/384620/cream-corn'
github:             'https://github.com/johnhatvani'
